apiVersion: v1
kind: Service
metadata:
  name: candidate-matching-service
spec:
  type: LoadBalancer
  selector:
    app: candidate-matching
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
